version: 2

jobs:
  build:
    docker:
      - image: golang:1.12.7
    working_directory: /src
    steps:
      - checkout
      - run:
          name: Download dependencies
          environment:
            GOPROXY: https://proxy.golang.org
          command: |
            go mod download
      - run:
          name: Test
          command: |
            go test -cover -race ./... 
      - run:
          name: Install golangci-lnit
          environment:
            GOLANGCI_LINT_TAG: v1.17.1
          command: |
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -d -b $GOPATH/bin $GOLANGCI_LINT_TAG
      - run:
          name: Lint
          command: |
            golangci-lint run ./... -v
      - run:
          name: Build
          environment:
              CGO_ENABLED: 0
          command: |
            go install -ldflags="-s -w"
            du -h $(which func)
            func --help
