version: 2

jobs:
  build:
    docker:
      - image: golang:1.12.7
      - image: minio/minio
        environment:
          MINIO_ACCESS_KEY: miniotest
          MINIO_SECRET_KEY: miniotest
          MINIO_HTTP_TRACE: /dev/stderr
        command: server /data
      - image: amazon/dynamodb-local
    working_directory: /src
    steps:
      - checkout
      - run:
          name: Download dependencies
          environment:
            GOPROXY: https://proxy.golang.org
          command: |
            go mod download
      - run:
          name: Test
          environment:
            TEST_S3_ACCESS_KEY: miniotest
            TEST_S3_SECRET_KEY: miniotest
            TEST_S3_REGION: us-east-1
            TEST_S3_ENDPOINT: "http://localhost:9000"
            TEST_DYNAMODB_REGION: local
            TEST_DYNAMODB_ACCESS_KEY: local
            TEST_DYNAMODB_SECRET_KEY: local
            TEST_DYNAMODB_ENDPOINT: "http://localhost:8000"
          command: |
            go test -cover -race -tags integration ./... 
      - run:
          name: Install golangci-lnit
          environment:
            GOLANGCI_LINT_TAG: v1.17.1
          command: |
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -d -b $GOPATH/bin $GOLANGCI_LINT_TAG
      - run:
          name: Lint
          command: |
            golangci-lint run ./... -v
      - run:
          name: Build
          environment:
              CGO_ENABLED: 0
          command: |
            go install -ldflags="-s -w"
            du -h $(which func)
            func --help
