// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ApplyRequest is the request to send to Apply.
type ApplyRequest struct {
	// Namespace is the namespace to apply resource changes to.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Config is the configuration to apply.
	//
	// The content should be a json encoded *hclpack.Body.
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyRequest) Reset()         { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()    {}
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *ApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRequest.Unmarshal(m, b)
}
func (m *ApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRequest.Marshal(b, m, deterministic)
}
func (m *ApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRequest.Merge(m, src)
}
func (m *ApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyRequest.Size(m)
}
func (m *ApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRequest proto.InternalMessageInfo

func (m *ApplyRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ApplyRequest) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

// ApplyResponse is returned from applying resources.
//
// The response may contain an UploadRequest, in which case the apply is
// rejected due to missing source code. The source code should be uploaded and
// then Apply should be retried.
type ApplyResponse struct {
	// SourcesRequired is set if source code uploads are required.
	SourcesRequired      []*SourceRequest `protobuf:"bytes,1,rep,name=sources_required,json=sourcesRequired,proto3" json:"sources_required,omitempty"`
	Diagnostics          []*Diagnostic    `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ApplyResponse) Reset()         { *m = ApplyResponse{} }
func (m *ApplyResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyResponse) ProtoMessage()    {}
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *ApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyResponse.Unmarshal(m, b)
}
func (m *ApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyResponse.Marshal(b, m, deterministic)
}
func (m *ApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyResponse.Merge(m, src)
}
func (m *ApplyResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyResponse.Size(m)
}
func (m *ApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyResponse proto.InternalMessageInfo

func (m *ApplyResponse) GetSourcesRequired() []*SourceRequest {
	if m != nil {
		return m.SourcesRequired
	}
	return nil
}

func (m *ApplyResponse) GetDiagnostics() []*Diagnostic {
	if m != nil {
		return m.Diagnostics
	}
	return nil
}

// An SourceRequest describes a single upload request.
type SourceRequest struct {
	// Key is the key of the source code to upload.
	// The digest maps back to a resource in the ApplyRequest config.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Url is the destination URL to upload to.
	// The request should be done as a HTTP PUT.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Headers include the additional headers that must be set on the upload.
	Headers              map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SourceRequest) Reset()         { *m = SourceRequest{} }
func (m *SourceRequest) String() string { return proto.CompactTextString(m) }
func (*SourceRequest) ProtoMessage()    {}
func (*SourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *SourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceRequest.Unmarshal(m, b)
}
func (m *SourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceRequest.Marshal(b, m, deterministic)
}
func (m *SourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceRequest.Merge(m, src)
}
func (m *SourceRequest) XXX_Size() int {
	return xxx_messageInfo_SourceRequest.Size(m)
}
func (m *SourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SourceRequest proto.InternalMessageInfo

func (m *SourceRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SourceRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SourceRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

type Diagnostic struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Summary              string   `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Detail               string   `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Subject              *Range   `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Context              *Range   `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Diagnostic) Reset()         { *m = Diagnostic{} }
func (m *Diagnostic) String() string { return proto.CompactTextString(m) }
func (*Diagnostic) ProtoMessage()    {}
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *Diagnostic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Diagnostic.Unmarshal(m, b)
}
func (m *Diagnostic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Diagnostic.Marshal(b, m, deterministic)
}
func (m *Diagnostic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Diagnostic.Merge(m, src)
}
func (m *Diagnostic) XXX_Size() int {
	return xxx_messageInfo_Diagnostic.Size(m)
}
func (m *Diagnostic) XXX_DiscardUnknown() {
	xxx_messageInfo_Diagnostic.DiscardUnknown(m)
}

var xxx_messageInfo_Diagnostic proto.InternalMessageInfo

func (m *Diagnostic) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *Diagnostic) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Diagnostic) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Diagnostic) GetSubject() *Range {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *Diagnostic) GetContext() *Range {
	if m != nil {
		return m.Context
	}
	return nil
}

type Range struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Start                *Pos     `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  *Pos     `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (m *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(m, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Range) GetStart() *Pos {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Range) GetEnd() *Pos {
	if m != nil {
		return m.End
	}
	return nil
}

type Pos struct {
	Line                 int64    `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Column               int64    `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	Byte                 int64    `protobuf:"varint,3,opt,name=byte,proto3" json:"byte,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos) Reset()         { *m = Pos{} }
func (m *Pos) String() string { return proto.CompactTextString(m) }
func (*Pos) ProtoMessage()    {}
func (*Pos) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *Pos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos.Unmarshal(m, b)
}
func (m *Pos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos.Marshal(b, m, deterministic)
}
func (m *Pos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos.Merge(m, src)
}
func (m *Pos) XXX_Size() int {
	return xxx_messageInfo_Pos.Size(m)
}
func (m *Pos) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos.DiscardUnknown(m)
}

var xxx_messageInfo_Pos proto.InternalMessageInfo

func (m *Pos) GetLine() int64 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *Pos) GetColumn() int64 {
	if m != nil {
		return m.Column
	}
	return 0
}

func (m *Pos) GetByte() int64 {
	if m != nil {
		return m.Byte
	}
	return 0
}

func init() {
	proto.RegisterType((*ApplyRequest)(nil), "io.func.ApplyRequest")
	proto.RegisterType((*ApplyResponse)(nil), "io.func.ApplyResponse")
	proto.RegisterType((*SourceRequest)(nil), "io.func.SourceRequest")
	proto.RegisterMapType((map[string]string)(nil), "io.func.SourceRequest.HeadersEntry")
	proto.RegisterType((*Diagnostic)(nil), "io.func.Diagnostic")
	proto.RegisterType((*Range)(nil), "io.func.Range")
	proto.RegisterType((*Pos)(nil), "io.func.Pos")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x55, 0xd6, 0x9b, 0xed, 0x76, 0xda, 0x85, 0x95, 0x81, 0xca, 0xaa, 0x10, 0xaa, 0xc2, 0x25,
	0xa7, 0x1c, 0x8a, 0x40, 0x68, 0xa5, 0x3d, 0x2c, 0xec, 0x4a, 0x1c, 0x2b, 0x73, 0xe3, 0x82, 0x5c,
	0x67, 0x5a, 0x02, 0xa9, 0x9d, 0xb5, 0x1d, 0x44, 0x3e, 0x81, 0x3f, 0xe1, 0xc4, 0x37, 0x22, 0x3b,
	0x6e, 0xb6, 0xac, 0x7a, 0x9b, 0x37, 0xef, 0xcd, 0x7b, 0x1e, 0x65, 0x02, 0x63, 0xd3, 0xc8, 0xa2,
	0x31, 0xda, 0x69, 0x3a, 0xaa, 0x74, 0xb1, 0x69, 0x95, 0xcc, 0x6e, 0x61, 0x7a, 0xd3, 0x34, 0x75,
	0xc7, 0xf1, 0xbe, 0x45, 0xeb, 0xe8, 0x4b, 0x18, 0x2b, 0xb1, 0x43, 0xdb, 0x08, 0x89, 0x2c, 0x59,
	0x24, 0xf9, 0x98, 0x3f, 0x34, 0xe8, 0x0c, 0xce, 0xa4, 0x56, 0x9b, 0x6a, 0xcb, 0x4e, 0x16, 0x49,
	0x3e, 0xe5, 0x11, 0x65, 0xbf, 0x13, 0xb8, 0x88, 0x36, 0xb6, 0xd1, 0xca, 0x22, 0xbd, 0x81, 0x4b,
	0xab, 0x5b, 0x23, 0xd1, 0x7e, 0x35, 0x78, 0xdf, 0x56, 0x06, 0x4b, 0x96, 0x2c, 0x48, 0x3e, 0x59,
	0xce, 0x8a, 0x98, 0x5d, 0x7c, 0x0e, 0x82, 0x98, 0xcc, 0x9f, 0x46, 0x3d, 0x8f, 0x72, 0xfa, 0x16,
	0x26, 0x65, 0x25, 0xb6, 0x4a, 0x5b, 0x57, 0x49, 0xcb, 0x4e, 0xc2, 0xf4, 0xb3, 0x61, 0xfa, 0x76,
	0xe0, 0xf8, 0xa1, 0x2e, 0xfb, 0x9b, 0xc0, 0xc5, 0x7f, 0xce, 0xf4, 0x12, 0xc8, 0x0f, 0xec, 0xe2,
	0x36, 0xbe, 0xf4, 0x9d, 0xd6, 0xd4, 0x61, 0x89, 0x31, 0xf7, 0x25, 0xbd, 0x86, 0xd1, 0x37, 0x14,
	0x25, 0x1a, 0xcb, 0x48, 0x08, 0x7a, 0x7d, 0xfc, 0x99, 0xc5, 0xa7, 0x5e, 0x75, 0xa7, 0x9c, 0xe9,
	0xf8, 0x7e, 0x66, 0x7e, 0x05, 0xd3, 0x43, 0xe2, 0x48, 0xe4, 0x73, 0x48, 0x7f, 0x8a, 0xba, 0xc5,
	0x18, 0xda, 0x83, 0xab, 0x93, 0xf7, 0x49, 0xf6, 0x27, 0x01, 0x78, 0x58, 0xc6, 0x0b, 0xd1, 0x18,
	0x6d, 0xc2, 0xf0, 0x39, 0xef, 0x01, 0x65, 0x30, 0xb2, 0xed, 0x6e, 0x27, 0x4c, 0x17, 0x0d, 0xf6,
	0xd0, 0x7f, 0x93, 0x12, 0x9d, 0xa8, 0x6a, 0x46, 0x02, 0x11, 0x11, 0xcd, 0xfd, 0xc4, 0xfa, 0x3b,
	0x4a, 0xc7, 0x4e, 0x17, 0x49, 0x3e, 0x59, 0x3e, 0x19, 0x36, 0xe2, 0x42, 0x6d, 0x91, 0xef, 0x69,
	0xaf, 0x94, 0x5a, 0x39, 0xfc, 0xe5, 0x58, 0x7a, 0x5c, 0x19, 0xe9, 0x6c, 0x0b, 0x69, 0xe8, 0xd0,
	0x39, 0x9c, 0x6f, 0xaa, 0x1a, 0xfd, 0x65, 0xc4, 0x25, 0x07, 0x4c, 0x33, 0x48, 0xad, 0x13, 0xc6,
	0x85, 0x87, 0x4e, 0x96, 0xd3, 0xc1, 0x6c, 0xa5, 0x2d, 0xef, 0x29, 0xfa, 0x0a, 0x08, 0xaa, 0x32,
	0xbc, 0xf8, 0xb1, 0xc2, 0x13, 0xd9, 0x1d, 0x90, 0x95, 0xb6, 0x94, 0xc2, 0x69, 0x5d, 0xa9, 0x3e,
	0x82, 0xf0, 0x50, 0xf7, 0x37, 0x58, 0xb7, 0x3b, 0x15, 0xfc, 0x09, 0x8f, 0xc8, 0x6b, 0xd7, 0x9d,
	0xc3, 0xe0, 0x49, 0x78, 0xa8, 0x97, 0xd7, 0x40, 0xf8, 0xea, 0x23, 0x7d, 0x07, 0x69, 0xb8, 0x4e,
	0xfa, 0x62, 0x48, 0x3a, 0x3c, 0xfa, 0xf9, 0xec, 0x71, 0xbb, 0x3f, 0xe2, 0x0f, 0xe9, 0x17, 0x62,
	0x1a, 0xb9, 0x3e, 0x0b, 0xff, 0xcc, 0x9b, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x99, 0x0a, 0xb9,
	0xd9, 0x40, 0x03, 0x00, 0x00,
}
