// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ApplyRequest is the request to send to Apply.
type ApplyRequest struct {
	// Namespace is the namespace to apply resource changes to.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Config is the configuration to apply.
	//
	// The content should be a json encoded *hclpack.Body.
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyRequest) Reset()         { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()    {}
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_04be6b7d2de8c49b, []int{0}
}
func (m *ApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRequest.Unmarshal(m, b)
}
func (m *ApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRequest.Marshal(b, m, deterministic)
}
func (dst *ApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRequest.Merge(dst, src)
}
func (m *ApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyRequest.Size(m)
}
func (m *ApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRequest proto.InternalMessageInfo

func (m *ApplyRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ApplyRequest) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

// ApplyResponse is returned from applying resources.
//
// The response may contain an UploadRequest, in which case the apply is
// rejected due to missing source code. The source code should be uploaded and
// then Apply should be retried.
type ApplyResponse struct {
	// SourcesRequired is set if source code uploads are required.
	SourcesRequired      []*SourceRequest `protobuf:"bytes,1,rep,name=sources_required,json=sourcesRequired,proto3" json:"sources_required,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ApplyResponse) Reset()         { *m = ApplyResponse{} }
func (m *ApplyResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyResponse) ProtoMessage()    {}
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_04be6b7d2de8c49b, []int{1}
}
func (m *ApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyResponse.Unmarshal(m, b)
}
func (m *ApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyResponse.Marshal(b, m, deterministic)
}
func (dst *ApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyResponse.Merge(dst, src)
}
func (m *ApplyResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyResponse.Size(m)
}
func (m *ApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyResponse proto.InternalMessageInfo

func (m *ApplyResponse) GetSourcesRequired() []*SourceRequest {
	if m != nil {
		return m.SourcesRequired
	}
	return nil
}

// An SourceRequest describes a single upload request.
type SourceRequest struct {
	// Digest is the digest to upload.
	// The digest maps back to a resource in the ApplyRequest config.
	Digest string `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	// Url is the destination URL to upload to.
	// The request should be done as a HTTP PUT.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Headers include the additional headers that must be set on the upload.
	Headers              map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SourceRequest) Reset()         { *m = SourceRequest{} }
func (m *SourceRequest) String() string { return proto.CompactTextString(m) }
func (*SourceRequest) ProtoMessage()    {}
func (*SourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_04be6b7d2de8c49b, []int{2}
}
func (m *SourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceRequest.Unmarshal(m, b)
}
func (m *SourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceRequest.Marshal(b, m, deterministic)
}
func (dst *SourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceRequest.Merge(dst, src)
}
func (m *SourceRequest) XXX_Size() int {
	return xxx_messageInfo_SourceRequest.Size(m)
}
func (m *SourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SourceRequest proto.InternalMessageInfo

func (m *SourceRequest) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *SourceRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SourceRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func init() {
	proto.RegisterType((*ApplyRequest)(nil), "io.func.ApplyRequest")
	proto.RegisterType((*ApplyResponse)(nil), "io.func.ApplyResponse")
	proto.RegisterType((*SourceRequest)(nil), "io.func.SourceRequest")
	proto.RegisterMapType((map[string]string)(nil), "io.func.SourceRequest.HeadersEntry")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_rpc_04be6b7d2de8c49b) }

var fileDescriptor_rpc_04be6b7d2de8c49b = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xc9, 0x6a, 0x37, 0xfa, 0xec, 0x70, 0x04, 0x2d, 0x65, 0x78, 0x28, 0xf5, 0xd2, 0x53,
	0x0f, 0x13, 0x44, 0x06, 0x0a, 0x13, 0x15, 0xcf, 0xf1, 0xe6, 0x45, 0x6a, 0xfa, 0x36, 0x8b, 0x35,
	0xc9, 0x92, 0x46, 0xe8, 0xf7, 0xf2, 0x03, 0x4a, 0xdb, 0xa8, 0x53, 0x76, 0x7b, 0xef, 0xe5, 0x97,
	0xfc, 0x1e, 0xff, 0x40, 0xa0, 0x15, 0xcf, 0x95, 0x96, 0x8d, 0xa4, 0x93, 0x4a, 0xe6, 0x6b, 0x2b,
	0x78, 0x7a, 0x0b, 0xe1, 0x4a, 0xa9, 0xba, 0x65, 0xb8, 0xb5, 0x68, 0x1a, 0x7a, 0x0a, 0x81, 0x28,
	0xde, 0xd1, 0xa8, 0x82, 0x63, 0x4c, 0x12, 0x92, 0x05, 0xec, 0x77, 0x40, 0x23, 0x18, 0x73, 0x29,
	0xd6, 0xd5, 0x26, 0x1e, 0x25, 0x24, 0x0b, 0x99, 0xeb, 0x52, 0x06, 0x53, 0xf7, 0x8a, 0x51, 0x52,
	0x18, 0xa4, 0x2b, 0x98, 0x19, 0x69, 0x35, 0x47, 0xf3, 0xac, 0x71, 0x6b, 0x2b, 0x8d, 0x65, 0x4c,
	0x12, 0x2f, 0x3b, 0x5c, 0x44, 0xb9, 0x53, 0xe7, 0x8f, 0x3d, 0xe0, 0xc4, 0xec, 0xc8, 0xf1, 0xcc,
	0xe1, 0xe9, 0x27, 0x81, 0xe9, 0x1f, 0xa4, 0xb3, 0x97, 0xd5, 0x06, 0x4d, 0xe3, 0x16, 0x73, 0x1d,
	0x9d, 0x81, 0x67, 0x75, 0xdd, 0xaf, 0x14, 0xb0, 0xae, 0xa4, 0x57, 0x30, 0x79, 0xc5, 0xa2, 0x44,
	0x6d, 0x62, 0xaf, 0xb7, 0x9e, 0xed, 0xb7, 0xe6, 0x0f, 0x03, 0x75, 0x27, 0x1a, 0xdd, 0xb2, 0xef,
	0x3b, 0xf3, 0x25, 0x84, 0xbb, 0x07, 0x9d, 0xe0, 0x0d, 0x5b, 0x67, 0xed, 0x4a, 0x7a, 0x0c, 0xfe,
	0x47, 0x51, 0x5b, 0x74, 0xd2, 0xa1, 0x59, 0x8e, 0x2e, 0xc9, 0xe2, 0x1a, 0x0e, 0xee, 0xad, 0xe0,
	0xf4, 0x02, 0xfc, 0x3e, 0x12, 0x7a, 0xf2, 0xa3, 0xde, 0x0d, 0x7a, 0x1e, 0xfd, 0x1f, 0x0f, 0xc9,
	0xdd, 0xf8, 0x4f, 0x9e, 0x56, 0xfc, 0x65, 0xdc, 0xff, 0xd3, 0xf9, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x05, 0x92, 0xde, 0xdc, 0xb4, 0x01, 0x00, 0x00,
}
