// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ApplyRequest is the request to send to Apply.
type ApplyRequest struct {
	// Namespace is the namespace to apply resource changes to.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Config is the configuration to apply.
	//
	// The content should be a json encoded *hclpack.Body.
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyRequest) Reset()         { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()    {}
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4eea0370b35b666b, []int{0}
}
func (m *ApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRequest.Unmarshal(m, b)
}
func (m *ApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRequest.Marshal(b, m, deterministic)
}
func (dst *ApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRequest.Merge(dst, src)
}
func (m *ApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyRequest.Size(m)
}
func (m *ApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRequest proto.InternalMessageInfo

func (m *ApplyRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ApplyRequest) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

// ApplyResponse is returned from applying resources.
//
// The response may contain an UploadRequest, in which case the apply is
// rejected due to missing source code. The source code should be uploaded and
// then Apply should be retried.
type ApplyResponse struct {
	// Types that are valid to be assigned to Response:
	//	*ApplyResponse_SourceRequest
	Response             isApplyResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ApplyResponse) Reset()         { *m = ApplyResponse{} }
func (m *ApplyResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyResponse) ProtoMessage()    {}
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4eea0370b35b666b, []int{1}
}
func (m *ApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyResponse.Unmarshal(m, b)
}
func (m *ApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyResponse.Marshal(b, m, deterministic)
}
func (dst *ApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyResponse.Merge(dst, src)
}
func (m *ApplyResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyResponse.Size(m)
}
func (m *ApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyResponse proto.InternalMessageInfo

type isApplyResponse_Response interface {
	isApplyResponse_Response()
}

type ApplyResponse_SourceRequest struct {
	SourceRequest *SourceRequired `protobuf:"bytes,1,opt,name=source_request,json=sourceRequest,proto3,oneof"`
}

func (*ApplyResponse_SourceRequest) isApplyResponse_Response() {}

func (m *ApplyResponse) GetResponse() isApplyResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ApplyResponse) GetSourceRequest() *SourceRequired {
	if x, ok := m.GetResponse().(*ApplyResponse_SourceRequest); ok {
		return x.SourceRequest
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ApplyResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ApplyResponse_OneofMarshaler, _ApplyResponse_OneofUnmarshaler, _ApplyResponse_OneofSizer, []interface{}{
		(*ApplyResponse_SourceRequest)(nil),
	}
}

func _ApplyResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ApplyResponse)
	// response
	switch x := m.Response.(type) {
	case *ApplyResponse_SourceRequest:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SourceRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ApplyResponse.Response has unexpected type %T", x)
	}
	return nil
}

func _ApplyResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ApplyResponse)
	switch tag {
	case 1: // response.source_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SourceRequired)
		err := b.DecodeMessage(msg)
		m.Response = &ApplyResponse_SourceRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ApplyResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ApplyResponse)
	// response
	switch x := m.Response.(type) {
	case *ApplyResponse_SourceRequest:
		s := proto.Size(x.SourceRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// An UploadRequest contains the required sources to upload.
type SourceRequired struct {
	Uploads              []*UploadRequest `protobuf:"bytes,1,rep,name=uploads,proto3" json:"uploads,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SourceRequired) Reset()         { *m = SourceRequired{} }
func (m *SourceRequired) String() string { return proto.CompactTextString(m) }
func (*SourceRequired) ProtoMessage()    {}
func (*SourceRequired) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4eea0370b35b666b, []int{2}
}
func (m *SourceRequired) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceRequired.Unmarshal(m, b)
}
func (m *SourceRequired) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceRequired.Marshal(b, m, deterministic)
}
func (dst *SourceRequired) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceRequired.Merge(dst, src)
}
func (m *SourceRequired) XXX_Size() int {
	return xxx_messageInfo_SourceRequired.Size(m)
}
func (m *SourceRequired) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceRequired.DiscardUnknown(m)
}

var xxx_messageInfo_SourceRequired proto.InternalMessageInfo

func (m *SourceRequired) GetUploads() []*UploadRequest {
	if m != nil {
		return m.Uploads
	}
	return nil
}

// An UploadRequest describes a single upload request.
type UploadRequest struct {
	// Digest is the digest to upload.
	// The digest maps back to a resource in the ApplyRequest config.
	Digest string `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	// Url is the destination URL to upload to.
	// The request should be done as a HTTP PUT.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Headers include the additional headers that must be set on the upload.
	Headers              map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_4eea0370b35b666b, []int{3}
}
func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (dst *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(dst, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetDigest() string {
	if m != nil {
		return m.Digest
	}
	return ""
}

func (m *UploadRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UploadRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func init() {
	proto.RegisterType((*ApplyRequest)(nil), "func.ApplyRequest")
	proto.RegisterType((*ApplyResponse)(nil), "func.ApplyResponse")
	proto.RegisterType((*SourceRequired)(nil), "func.SourceRequired")
	proto.RegisterType((*UploadRequest)(nil), "func.UploadRequest")
	proto.RegisterMapType((map[string]string)(nil), "func.UploadRequest.HeadersEntry")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_4eea0370b35b666b) }

var fileDescriptor_api_4eea0370b35b666b = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4b, 0x4b, 0xc3, 0x40,
	0x10, 0xc7, 0x4d, 0xd3, 0x87, 0x99, 0x3e, 0x90, 0x6d, 0x91, 0x50, 0x3c, 0x84, 0x9c, 0x7a, 0x31,
	0x48, 0xbd, 0x94, 0x82, 0x88, 0x45, 0xa5, 0xe7, 0x15, 0x2f, 0xbd, 0xc8, 0x9a, 0x4c, 0x6b, 0x30,
	0x26, 0xeb, 0x6e, 0x56, 0xe8, 0xc7, 0xf2, 0x1b, 0xca, 0x3e, 0xaa, 0x0d, 0x78, 0x9b, 0xf9, 0xcf,
	0xec, 0xff, 0xb7, 0x33, 0x03, 0x01, 0xe3, 0x79, 0xc2, 0x45, 0x55, 0x57, 0xa4, 0xbd, 0x55, 0x65,
	0x1a, 0xdf, 0xc3, 0xe0, 0x8e, 0xf3, 0x62, 0x4f, 0xf1, 0x53, 0xa1, 0xac, 0xc9, 0x05, 0x04, 0x25,
	0xfb, 0x40, 0xc9, 0x59, 0x8a, 0xa1, 0x17, 0x79, 0xb3, 0x80, 0xfe, 0x09, 0xe4, 0x1c, 0xba, 0x69,
	0x55, 0x6e, 0xf3, 0x5d, 0xd8, 0x8a, 0xbc, 0xd9, 0x80, 0xba, 0x2c, 0xde, 0xc0, 0xd0, 0xb9, 0x48,
	0x5e, 0x95, 0x12, 0xc9, 0x0d, 0x8c, 0x64, 0xa5, 0x44, 0x8a, 0x2f, 0xc2, 0x1a, 0x1b, 0xaf, 0xfe,
	0x7c, 0x92, 0x68, 0x6a, 0xf2, 0x64, 0x6a, 0x9a, 0x99, 0x0b, 0xcc, 0xd6, 0x27, 0x74, 0x28, 0x7f,
	0x15, 0x94, 0xf5, 0x0a, 0xe0, 0x54, 0x38, 0xab, 0xf8, 0x16, 0x46, 0xcd, 0x76, 0x72, 0x09, 0x3d,
	0xc5, 0x8b, 0x8a, 0x65, 0x32, 0xf4, 0x22, 0x7f, 0xd6, 0x9f, 0x8f, 0xad, 0xeb, 0xb3, 0x11, 0x9d,
	0x07, 0x3d, 0xf4, 0xc4, 0xdf, 0x1e, 0x0c, 0x1b, 0x25, 0x3d, 0x46, 0x96, 0xef, 0x0e, 0xbf, 0x0a,
	0xa8, 0xcb, 0xc8, 0x19, 0xf8, 0x4a, 0x14, 0x66, 0xb6, 0x80, 0xea, 0x90, 0x2c, 0xa1, 0xf7, 0x86,
	0x2c, 0x43, 0x21, 0x43, 0xdf, 0xa0, 0xa2, 0x7f, 0x50, 0xc9, 0xda, 0xb6, 0x3c, 0x94, 0xb5, 0xd8,
	0xd3, 0xc3, 0x83, 0xe9, 0x12, 0x06, 0xc7, 0x05, 0xed, 0xfe, 0x8e, 0x7b, 0x87, 0xd4, 0x21, 0x99,
	0x40, 0xe7, 0x8b, 0x15, 0x0a, 0x1d, 0xd1, 0x26, 0xcb, 0xd6, 0xc2, 0x9b, 0x2f, 0xa0, 0xfd, 0xa8,
	0xca, 0x94, 0x5c, 0x41, 0xc7, 0x2c, 0x96, 0x10, 0xcb, 0x3d, 0xbe, 0xd5, 0x74, 0xdc, 0xd0, 0xec,
	0xba, 0x56, 0x9d, 0x8d, 0xcf, 0x78, 0xfe, 0xda, 0x35, 0x47, 0xbe, 0xfe, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x50, 0x71, 0xf3, 0xda, 0xf1, 0x01, 0x00, 0x00,
}
